### ISSUE TITLE
End and Nether are still broken

### ISSUE THREAD

**Issue by ThomasHineXYZ** [PawekPL/minecraft-dimension-status-datapack#2]
They are "the_end" and "the_nether".

https://github.com/PawekPL/minecraft-dimension-detector-datapack/commit/ba9ae4d8f49bb226c15e4e14d3da6403d5de348b

**Comment by ThomasHineXYZ** [comment]
Hello. Was this fixed?

**Comment by pfiszer** [comment]
Yes. It was fixed a while ago, but I forgot to close the issue
